import os

SECRET_KEY = os.urandom(24).hex()
SQLALCHEMY_DATABASE_URI = "sqlite:///esports.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
JSONIFY_PRETTYPRINT_REGULAR = False
